/**
 * Golden vector conformance — TypeScript side.
 *
 * The vectors are generated by wp-portal-bridge/tools/generate-vectors.mjs
 * (the canonical algorithm definition) and asserted by BOTH the PHP plugin
 * suite and this file. Drift on either side fails that side's tests.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  EMPTY_BODY_SHA256,
  canonicalRequest,
  canonicalResponse,
  deriveKeyId,
  sha256Hex,
  sign,
  signRequest,
  verifyResponse,
} from "../src/hmac.js";

const here = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(
  readFileSync(join(here, "..", "..", "test", "vectors", "hmac-vectors.json"), "utf8")
) as {
  tmk: string;
  keyId: string;
  derivedKeyId: string;
  emptyBodySha256: string;
  requests: Array<{
    name: string;
    method: string;
    pathWithQuery: string;
    timestamp: number;
    nonce: string;
    body: string | null;
    bodySha256: string;
    canonical: string;
    signature: string;
  }>;
  responses: Array<{
    name: string;
    requestNonce: string;
    statusCode: number;
    responseTimestamp: number;
    responseBody: string;
    responseBodySha256: string;
    canonical: string;
    signature: string;
  }>;
};

test("empty body sha256 constant matches the vectors", () => {
  assert.equal(EMPTY_BODY_SHA256, vectors.emptyBodySha256);
  assert.equal(sha256Hex(""), vectors.emptyBodySha256);
});

test("key id derivation matches the canonical generator", () => {
  assert.equal(deriveKeyId(vectors.tmk), vectors.derivedKeyId);
});

for (const vector of vectors.requests) {
  test(`request vector: ${vector.name}`, () => {
    const bodySha = vector.body === null ? EMPTY_BODY_SHA256 : sha256Hex(vector.body);
    assert.equal(bodySha, vector.bodySha256, "body sha");

    const canonical = canonicalRequest(
      vector.method,
      vector.pathWithQuery,
      vector.timestamp,
      vector.nonce,
      bodySha
    );
    assert.equal(canonical, vector.canonical, "canonical string");
    assert.equal(sign(vectors.tmk, canonical), vector.signature, "signature");

    // The header builder must reproduce the same signature end-to-end.
    const headers = signRequest({
      tmk: vectors.tmk,
      method: vector.method,
      pathWithQuery: vector.pathWithQuery,
      body: vector.body,
      timestamp: vector.timestamp,
      nonce: vector.nonce,
      keyId: vectors.keyId,
    });
    assert.equal(headers["X-Portal-Signature"], vector.signature);
    assert.equal(headers["X-Portal-Body-SHA256"], vector.bodySha256);
    assert.equal(headers["X-Portal-Timestamp"], String(vector.timestamp));
  });
}

for (const vector of vectors.responses) {
  test(`response vector: ${vector.name}`, () => {
    const canonical = canonicalResponse(
      vector.requestNonce,
      vector.statusCode,
      vector.responseTimestamp,
      vector.responseBodySha256
    );
    assert.equal(canonical, vector.canonical, "canonical string");
    assert.equal(sign(vectors.tmk, canonical), vector.signature, "signature");

    // verifyResponse accepts the exact signed reply…
    assert.equal(
      verifyResponse({
        tmk: vectors.tmk,
        requestNonce: vector.requestNonce,
        statusCode: vector.statusCode,
        body: vector.responseBody,
        headers: {
          timestamp: String(vector.responseTimestamp),
          bodySha256: vector.responseBodySha256,
          signature: vector.signature,
        },
      }),
      "valid"
    );

    // …rejects a tampered body…
    assert.equal(
      verifyResponse({
        tmk: vectors.tmk,
        requestNonce: vector.requestNonce,
        statusCode: vector.statusCode,
        body: vector.responseBody + " ",
        headers: {
          timestamp: String(vector.responseTimestamp),
          bodySha256: vector.responseBodySha256,
          signature: vector.signature,
        },
      }),
      "invalid"
    );

    // …and reports unsigned when headers are absent.
    assert.equal(
      verifyResponse({
        tmk: vectors.tmk,
        requestNonce: vector.requestNonce,
        statusCode: vector.statusCode,
        body: vector.responseBody,
        headers: {},
      }),
      "unsigned"
    );
  });
}
